name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Cambia a '4.8' si usas .NET Framework 4.8

      - name: Restore dependencies
        run: dotnet restore MiAplicacion.sln  # Cambia al nombre de tu solución

      - name: Build
        run: dotnet build MiAplicacion.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true  # Ignora errores si no hay pruebas aún

      - name: Publish
        run: dotnet publish MiAplicacion.csproj --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish/

      - name: Deploy (Placeholder)
        run: echo "Configura aquí el despliegue según tu entorno"
